spring.application.name=sesac
server.port=8084

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb

spring.jpa.show_sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true

spring.h2.console.enabled=true

spring.sql.init.mode=always

sesac.crawler.enabled=true
sesac.crawler.headless=true
sesac.crawler.wait-timeout-seconds=15
sesac.crawler.max-care-items=100
sesac.crawler.max-job-items=100
sesac.crawler.search-keyword=고립은둔청년
sesac.crawler.big-kinds-url=https://www.bigkinds.or.kr/
sesac.crawler.saramin-url=https://www.saramin.co.kr/zf_user/jobs/public/list
sesac.crawler.refresh-cron=0 50 23 * * *
